config/routes.rb
Rails.application.routes.draw do
  resources :favorites
  resources :visits
  resources :locations
  resources :users
  resources :pages

  root :to => "pages#index"
  get '/about', to: 'pages#about'

  get '/signup', to: 'users#new'
  get '/login', to: 'sessions#new'
  post '/sessions', to: 'sessions#create'
  get '/home', to: 'pages#index'
  delete '/logout', to: 'sessions#destroy'
  delete '/favorites/destroy/:user_id/:location_id', to: 'favorites#destroy'
  get '/favorites/new/:user_id/:location_id', to: 'favorites#create'
  
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/country.rb
class Country < ApplicationRecord
  has_many :locations
  has_many :users
end

app/models/favorite.rb
class Favorite < ApplicationRecord
    belongs_to :user
    belongs_to :location
end

app/models/location.rb
class Location < ApplicationRecord
    has_many :visits
    has_many :users, through: :visits
    belongs_to :country

    validates :name, :description, :country_id, presence:true
    validates :description, length: {maximum: 100}

    def owner
        User.all.find(self.user_id)
    end

    def fav_users
        Favorite.all.select do |fav|
            fav.location == self
        end.map do |fav|
            User.find(fav.user_id).full_name
        end
    end

    def self.top_five_locations
        Location.all.sort_by do |loc|
          loc.fav_users.count
        end.reverse[0..4]
    end

    def favorite?(user_id)
        Favorite.find_by(user_id: user_id, location: self)
    end
end

app/models/user.rb
class User < ApplicationRecord
    has_secure_password
    has_many :visits
    has_many :locations, through: :visits
    
    validates :first_name, :last_name, :email, presence: true

    def added_locations
        Location.all.select do |loc|
            loc.user_id == self.id
        end
    end

  def full_name
    [first_name, last_name].reject(&:blank?).join(' ').titleize
  end

  def fav_locations
    Favorite.all.select do |fav|
        fav.user == self
    end.map do |fav|
        Location.find(fav.location_id)
    end
  end

end

app/models/visit.rb
class Visit < ApplicationRecord
    belongs_to :user
    belongs_to :location
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base

  def logged_in?
    !session[:user_id].nil?
  end

  def authorized
    if !logged_in? 
      flash[:notice] = "Please log in first."
      redirect_to '/login'
    end
  end

  # def current_user
  #   if logged_in?
  #     @current_user = User.find(session[:user_id])
  #   end
  # end
end

app/controllers/favorites_controller.rb
class FavoritesController < ApplicationController
    def create
        fav = Favorite.find_or_create_by(user_id: params[:user_id], location_id: params[:location_id])
        redirect_to location_path(fav.location)
    end

    def destroy
        fav = Favorite.find_by(user_id: params[:user_id], location_id: params[:location_id])
        loc = fav.location
        fav.delete
        redirect_to location_path(loc)
    end
end

app/controllers/locations_controller.rb
class LocationsController < ApplicationController
    before_action :authorized, only: [:new, :create, :edit, :update]
    
    def index
        @locations = Location.all
    end

    def show
        set_location
    end

    def new
        @location = Location.new
    end

    def create
        @location = Location.create(location_params)
        if @location.valid?
            redirect_to location_path(@location)
        else
            flash.now[:error] = @location.errors.full_messages
            render :new
        end
    end

    def edit
        set_location
    end

    def update
        set_location
        @location.update(location_params)
        if @location.valid?
            redirect_to location_path(@location)
        else
            flash.now[:error] = @location.errors.full_messages
            render :new
        end
    end

    private

    def set_location
        @location = Location.find(params[:id])
    end

    def location_params
        params.require(:location).permit(:name, :description, :country_id, :user_id)
    end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  def index

  end
  
  def about 
  end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  def new
  end

  def create
    user = User.find_by(email: params[:email])
    if user 
      if user.authenticate(params[:password])
        session[:user_id] = user.id
        redirect_to user_path(user)
      else
        flash.now[:error] = user.errors.full_messages
        render :new
      end
    else
        flash.now[:error] = ["No user with that email."]
        render :new
    end
  end

  def destroy
    session.delete :user_id
    redirect_to "/"
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :authorized, only: [:show, :edit, :update]

  def index
    if params[:q]
      @user = User.find_by(email: params[:q])
    else
      @user = nil
    end
  end

  def new
    @user = User.new
  end

  def create
    @user = User.new(user_params)
    if @user.valid?
      @user.save
      session[:user_id] = @user.id
      redirect_to user_path(@user)
    else
      flash.now[:error] = @user.errors.full_messages
      render :new
    end
  end

  def show
    set_user
    @visit = Visit.new
  end

  def edit
    set_user
  end

  def update
    set_user
    @user.update(user_params)
    if @user.valid?
      redirect_to user_path(@user)
    else
      flash.now[:error] = @user.errors.full_messages
        render :edit
    end
  end


  private

  def set_user
    @user = User.find(params[:id])
  end

  def user_params
    params.require(:user).permit(:first_name, :last_name, :email, :country_id, :password, :password_confirmation)
  end

end

app/controllers/visits_controller.rb
class VisitsController < ApplicationController
  def create
    # byebug
    @visit = Visit.find_or_create_by(user_id: visit_params[:user_id], location_id: visit_params[:location_id])

    date = Date.civil(visit_params["visit_date(1i)"].to_i, visit_params["visit_date(2i)"].to_i, visit_params["visit_date(3i)"].to_i)
    @visit.visit_date = date
    @visit.save
    redirect_to user_path(@visit.user)
  end

  def destroy
    @visit = Visit.find(params[:id])
    @visit.delete
    redirect_to user_path(@visit.user)

  end

  private


  def visit_params
    params.require(:visit).permit(:user_id, :location_id, :visit_date)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/favorites_helper.rb
module FavoritesHelper
end

app/helpers/locations_helper.rb
module LocationsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/helpers/visits_helper.rb
module VisitsHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html style="background-image: linear-gradient(#deeafc, #d9faff">
  <head>
    <title>HiddenGems</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%# stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= stylesheet_link_tag "application.css" %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>

    <nav class="nav-bar">
      <ul>

        <li><%= link_to "Home", '/' %></li>
        <li><%= link_to "About", '/about' %></li>
        <li><%= link_to "Hidden Gem List", locations_path %></li>

        <% if session[:user_id] %>
          <li><%= link_to "Search User", users_path %></li>
          <li class="right"><a href="#">Hi <%= User.find(session[:user_id]).full_name %></a>
            <ul class="dropdown">
              <li><%= link_to "My Page", "/users/#{session[:user_id]}" %></li>
              <li><%= link_to "Log Out", "/logout", method: :delete %></li>
            </ul>
          </li>
        <% else %>
          <li class="right"><a href="#"> Log In / Register </a>
            <ul class="dropdown">
              <li><%= link_to "Log In", "/login", method: :get %></li>
              <li><%= link_to "Register", "/signup", method: :get %></li>
            </ul>
          </li>
        <% end %>
      </ul>
    </nav>

    <%= yield %>
  </body>
</html>

app/views/locations/edit.html.erb
<div class="page-wrap" >
    <h1>Edit Hidden Gem</h1>

    <% if flash.now[:error] %>
        <h3> Errors: </h3>
        <ul>
        <% flash.now[:error].each do |err| %>
            <%= err %><br>
        <% end %>
        </ul>
    <% end %>

    <% if session[:user_id] %>
        <%= form_for @location do |f| %>
            <%= f.label :name %>
            <%= f.text_field :name %>
            <br><br>
            <%= f.label :description %> (Max. 50 words) <br>
            <%= f.text_area :description %>
            <br><br>
            <%= f.label :country %>
            <%= f.collection_select :country_id, Country.all, :id, :name %>
            <%= f.hidden_field :user_id, value: session[:user_id] %>
            <br><br>
            <%= f.label :image_url %>
            <%= f.text_field :image_url %>
            <br>
            <%= f.submit %>
        <% end %>
    <% end %>
</div>

app/views/locations/index.html.erb
<div class="page-wrap" >
    <h1>Hidden Gems</h1>
    <ul>
    <% @locations.each do |loc| %>
        <li><%= link_to loc.name, location_path(loc) %></li>
    <% end %>
    </ul>

    <h3>Know any hidden gems to visit?</h3>
    <%= button_to "Add Hidden Gem!", new_location_path, method: :get %>
</div>

app/views/locations/new.html.erb
<div class="page-wrap" >
    <h1>Introduce a Hidden Gem!</h1>

    <% if flash.now[:error] %>
        <h3> Errors: </h3>
        <ul>
        <% flash.now[:error].each do |err| %>
            <%= err %><br>
        <% end %>
        </ul>
    <% end %>

    <% if session[:user_id] %>
        <%= form_for @location do |f| %>
            <%= f.label :name %>
            <%= f.text_field :name %>
            <br><br>
            <%= f.label :description %> (Max. 50 words)<br>
            <%= f.text_area :description %>
            <br><br>
            <%= f.label :country %>
            <%= f.collection_select :country_id, Country.all, :id, :name %>
            <%= f.hidden_field :user_id, value: session[:user_id] %>
            <br><br>
            <%= f.label :image_url %>
            <%= f.text_field :image_url %>
            <br>
            <%= f.submit %>
        <% end %>
    <% end %>
</div>

app/views/locations/show.html.erb
<div class="page-wrap" >
    <h1><%= @location.name %></h1>
    <h2>Country: <%= @location.country.name%></h2>
    <p><%= @location.description %></p>

    <div class="show-page">

        <% if @location.image_url %>
            <%= image_tag @location.image_url %>
        <% else %>
            <%= image_tag("no-image.png") %>
        <% end %>
    </div>
    <br>
    <h4>Favorites: <%= @location.fav_users.count %></h4> 
    <% if session[:user_id] %>
        <% if @location.favorite?(session[:user_id]) %>
            <div class="unfavorite">
                <%= button_to "", "/favorites/destroy/#{session[:user_id]}/#{@location.id}", method: :delete, class: "unfavorite" %>
            </div>
        <% else %>
            <div class="favorite">
                <%= button_to "", "/favorites/new/#{session[:user_id]}/#{@location.id}", method: :get%>
            </div>
            <% end %>
    <% end %>

    <% if session[:user_id] == @location.owner.id %>
        <h4>Hidden Gem Added By... You!</h4>
        <%= button_to "Edit Hidden Gem", edit_location_path, method: :get %>
    <% else %>
    <h4>Hidden Gem Added By <%= link_to @location.owner.full_name, user_path(@location.owner) %></h4>
    <% end %>

</div>

app/views/pages/about.html.erb
<div class="page-wrap about">
  <h1> About Hidden Gems </h1>

  <p> Tired of the Eiffel Tower, The Statue of Liberty, Buckingham Palace? 
  Tired of being pushed around by sweaty tourists with their selfie sticks? 
  Tired of being let down by overhyped tourist destinations?</p>
  <br>
  <p>Welcome to Hidden Gems, where you’ll discover precious diamonds of destinations, without the effort of digging. 
  Our spots are added by our very own users, locals that know every nook and cranny of their hometowns. 
  We want to help you on your journey towards becoming a Gem Master, discovering and conquering the multitude of hidden gems the world has to offer.</p>
  <br>
  <p>Ready to begin your quest? </p>
  <p><%= button_to "Register Here!", "/signup", method: :get %></p>

</div>

app/views/pages/index.html.erb
<div class="main-header">
 <%= image_tag("banner1.jpg", class:"banner-image") %>
 <h1 class="centered">Hidden Gems</h1>
</div>
<br>
<br>

<div class="page-wrap">
 <div class="container"
  <div class="container-text">
      <h1>Want a little taste?</h1>
      <h1>Here are some of our users' favorite hidden gems!</h1>
  </div>
  <div class="container-image">
    <%= image_tag("arrow.png") %>
  </div>
 </div>

 <br>

    <% Location.top_five_locations.each do |t| %>
      <div class="fav-locations">
        <% if t.image_url %>
          <%= image_tag t.image_url %>
        <% else %>
          <%= image_tag("no-image.png") %>
        <% end %>
        <div class="middle">
          <div class="text"><%= link_to t.name, location_path(t) %></div>
        </div>
      </div>
    <% end %>

  </div>
</div>

app/views/users/edit.html.erb
<div class="page-wrap" >
  <h1>Edit Your Profile</h1>
  <% if flash.now[:error] %>
    <% flash.now[:error].each do |error_msg| %>
      <li><%= error_msg %></li>
    <% end %><br>
  <% end %>

  <%= form_for @user do |f| %>
    <%= f.label :first_name %>
    <%= f.text_field :first_name %>
    <br><br>
    <%= f.label :last_name %>
    <%= f.text_field :last_name %>
    <br><br>
    <%= f.label :email %>
    <%= f.email_field :email %>
    <br><br>
    <%= f.label :country_id %>
    <%= f.collection_select :country_id, Country.all, :id, :name %>
    <br><br>
    <%= f.label :password %>
    <%= f.password_field :password %>
    <br><br>
    <%= f.label :password_confirmation %>
    <%= f.password_field :password_confirmation %>
    <%= f.submit %>
  <% end %>
</div>

app/views/users/index.html.erb
<div class="page-wrap" >
    <h1>Search for User by Email</h1>
    
    <%= form_tag users_path, method: :get do %>
        <%= text_field_tag :q %>
        <%= submit_tag "Search"%>
    <% end %>

    <br><br>
    <% if @user %>
        <%= link_to @user.full_name, user_path(@user) %>
    <% else %>
        No user with that email...
    <% end %>
</div>

app/views/users/new.html.erb
<div class="page-wrap" >
  <h1>Signup for Hidden Gems</h1>
  <% if flash.now[:error] %>
    <% flash.now[:error].each do |error_msg| %>
      <li><%= error_msg %></li>
    <% end %><br>
  <% end %>

  <%= form_for @user do |f| %>
    <%= f.label :first_name %>
    <%= f.text_field :first_name %>
    <br><br>
    <%= f.label :last_name %>
    <%= f.text_field :last_name %>
    <br><br>
    <%= f.label :email %>
    <%= f.email_field :email %>
    <br><br>
    <%= f.label :country_id %>
    <%= f.collection_select :country_id, Country.all, :id, :name %>
    <br><br>
    <%= f.label :password %>
    <%= f.password_field :password %>
    <br><br>
    <%= f.label :password_confirmation %>
    <%= f.password_field :password_confirmation %><br><br>
    <%= f.submit %>
  <% end %>
</div>

app/views/users/show.html.erb
<div class="page-wrap" > 
  <% if session[:user_id] == @user.id %>
    <h1> My Page </h1>
  <% else %>
    <h1><%= @user.full_name %></h1>
  <% end %>

  <br>

  <div class="column">

    <div class="block">
      <h2>Hidden Gems Visited:</h2><br>
      <ul>
        <% @user.visits.each do |visit| %>
        <li><%= link_to visit.location.name, location_path(visit.location) %> <br>(<%= visit.visit_date %>)</li>
          <% if session[:user_id] == @user.id %>
            <%= form_for visit, :method => :delete do |f| %>
              <%= f.submit "Remove Visit" %>
            <% end %>
          <% end %>
        <% end %>
      </ul>

      <% if session[:user_id] == @user.id %>
        <h3>Add a New Visit</h3>
        <%= form_for @visit do |f| %>
          <%= f.collection_select :location_id, Location.all, :id, :name %>
          <%= f.hidden_field :user_id, value: @user.id %>
          <%= f.date_select :visit_date %><br>
          <%= f.submit "Add Visit" %>
        <% end %>
      <% end %>
    </div>

    <br>

    <div class="block">
      <div class="block-2">
        <% if session[:user_id] == @user.id %>
          <h2>My Favorite Hidden Gems</h2>
        <% else %>
          <h2> <%=@user.full_name%>'s Favorite Gems </h2>
        <% end %>

        <% if @user.fav_locations.empty? %>
          <p>No Favorite Gems :(</p>
        <% else %>
          <ul>
            <% @user.fav_locations.each do |fav_location| %>
              <li><%= link_to fav_location.name, location_path(fav_location) %></li>
            <% end %>
          </ul>
        <% end %>
      </div>
      <br>

      <div class="block-2">
        <% if session[:user_id] == @user.id %>
          <h2>Gems Introduced</h2>
        <% else %>
          <h2>Gems Introduced by <%=@user.full_name%></h2>
        <% end %>

        <ul>
          <% @user.added_locations.each do |location| %>
            <li><%= link_to location.name, location_path(location) %></li>
          <% end %>
        </ul>

        <% if session[:user_id] == @user.id %>
          <%= button_to "Introduce A Hidden Gem", new_location_path, method: :get %>
        <% end %>
      </div>
    </div>
  </div>
</div>